### ISSUE TITLE
Remove "unity-native-plugin-sample-profiler"

### ISSUE THREAD

**Issue by aosoft** [aosoft/unity-native-plugin-rs#4]
@yjh0502

The confirmation was insufficient.  ["TrackEventProfiler"](https://github.com/Unity-Technologies/TraceEventProfiler) does not have a stated license, so I don't think a port of it should be included.
I'm sorry, but "unity-native-plugin-sample-profiler" will be removed, including its history.

"unity-native-plugin-sample-profiler" should be created as an independent repository. Change the link from README.md.

**Comment by yjh0502** [comment]
@aosoft `unity-native-plugin-sample-profiler` was actually an independent implementation that emits Trace Event Format from chrome project [1], which `TraceEventProfiler` does as well. IFAIK it should not be a problem as it is an independent implementation with same functionality, not a direct port.
Nontheless, I'm okay with your decision, thanks for sharing BTW!

[1] https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

**Comment by aosoft** [comment]
> @aosoft `unity-native-plugin-sample-profiler` was actually an independent implementation that emits Trace Event Format from chrome project [1], which `TraceEventProfiler` does as well. IFAIK it should not be a problem as it is an independent implementation with same functionality, not a direct port.
> Nontheless, I'm okay with your decision, thanks for sharing BTW!
> 
> [1] https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

Thank you for your reply.
I think "similar to ~" would be more appropriate than "a port of ~".
I would like to change the content of README.md and not remove the code.
