### ISSUE TITLE
Upgrade to newest Unity headers

### ISSUE THREAD

**Issue by ZhaoXiangXML** [aosoft/unity-native-plugin-rs#7]
Would you please kindly upgrade the native bindings to match the latest Unity headers?

I'd like to be able to use the new memory profiler APIs.

Thank you.

**Comment by ZhaoXiangXML** [comment]
It appears there are three Unity 6 headers missing:

- `IUnityMemoryManager.h`
- `IUnityEventQueue.h`
- `IUnityLog.h`

**Comment by ZhaoXiangXML** [comment]
I've created PR https://github.com/aosoft/unity-native-plugin-rs/pull/8 to solve this

**Comment by aosoft** [comment]
Thank you for you contribution.
I'll check it.

**Comment by ZhaoXiangXML** [comment]
@aosoft Would you please publish a new version on crates.io? Thanks.

**Comment by aosoft** [comment]
It has been published.
